### ISSUE TITLE
GetAll with no filtering ?

### ISSUE THREAD

**Issue by mRmEEeZ** [Tavenem/Blazor.IndexedDB#1]
Hello...

its a great library thanks...but it needs some updated tho...
i think it needs an update for the GetAll to filter out and limit with skip (paging)

**Comment by WilStead** [comment]
You're absolutely right. This library is in need of a major update with a more complete API.

I'd like v2 to fully implement my [IDataStore](https://github.com/Tavenem/DataStore) interface if possible, with full support for querying and paging operations.

**Comment by WilStead** [comment]
The first preview of v2 was just released.

You can get it on NuGet [here](https://www.nuget.org/packages/Tavenem.Blazor.IndexedDB/2.0.3-preview1) (make sure to enable preview versions).

I don't have a specific release date in mind yet for the stable release of v2.0. It now depends on my [DataStore](https://github.com/Tavenem/DataStore) library, also in prerelease. I don't feel like DataStore has seen enough field testing to promote it to stable yet. Once it's ready, a stable release of IndexedDb v2.0 will follow.

**Comment by WilStead** [comment]
Version 2.0 has been released.
