### ISSUE TITLE
Cant add additional objectStores because new version it' required

### ISSUE THREAD

**Issue by reengineeringdevops** [Tavenem/Blazor.IndexedDB#5]
To add a new object store in IndexedDB using the [idb](https://github.com/jakearchibald/idb) library, you need to increment the database version. This is a fundamental behavior of IndexedDB, not specific to the idb library.

When you create a new object store, it must be done during the upgrade phase. Incrementing the database version triggers the onupgradeneeded event, allowing you to modify the database structure, such as creating new object stores or indexes.

Example with idb
Suppose you have an existing database and want to add a new object store:

```
import { openDB } from 'idb';

const db = await openDB('MyDatabase', 2, {
  upgrade(db, oldVersion, newVersion, transaction) {
    if (oldVersion < 2) {
      // Create a new object store in version 2
      db.createObjectStore('NewStore', { keyPath: 'id' });
    }
  },
});
console.log('Object store successfully added');
```

Details:
Database version: The version is updated from 1 to 2. Incrementing the version is mandatory for making structural changes.
createObjectStore method: This can only be called during the onupgradeneeded event.
Backward compatibility: If you have users running a previous version of the database, the logic if (oldVersion < 2) ensures that the new object store is created only when needed.
Note:
If you don’t increment the version and try to add an object store, you’ll get an error because structural changes are not allowed during a normal transaction.

**Comment by WilStead** [comment]
That's a good summary of the behavior of IndexedDB and idb. I agree that the library should support multiple object stores without raising errors.

Your previous PR introduced dynamic version number changes, which I do not believe is a good practice. In my view, the application author should have direct control over the versioning process.

What are your expectations around this issue? Do you just need the error resolved, or do you have specific requirements to satisfy?

If you just need the library's current problem with creating more than one store fixed, my first thought is that the service registration could be changed to require all object stores to be provided during initial service registration. The `openDB` call in the TypeScript file could be revised to create all stores upon initial access, instead of just the one being queried. This would be a fairly simple change for me to implement.

**Comment by reengineeringdevops** [comment]
The goal is to allow the creation of multiple object stores, and I agree with doing this at the beginning of the database creation process and relative to the version specified during initialization. 
However, I believe there is a structural issue that persists. What would happen if a user wanted to add an object store at a later time ? As the library is currently structured, this would not be possible because there is no control over version updates, which risks making the library less flexible and therefore unsuitable for more complex and realistic application contexts. 
This is why, in my opinion, dynamic version updates could also be important.

**Comment by WilStead** [comment]
That's an interesting question.

My current thinking is that _dynamic_ schema updates would not be considered in-scope for this library as a built-in feature. I would typically expect schema changes to occur in between deployments as part of a larger code/architecture change.

That said, dynamic object store creation would be possible without introducing dynamic versioning behavior to the library itself. The service could simply be re-registered using the new version number, along with the new set of required object stores.

Would that satisfy your requirements for dynamic store creation? Or is there a reason you would need in-built library support for the feature?

**Comment by reengineeringdevops** [comment]
It would also be fine to re-register the service by incrementing the version number and adding the new objectStores.
It would also be interesting to implement, if not already available, a dynamic addition of objectStores using reflection, based on the version specified during initialization. Something similar to how migrations work in Entity Framework. Anyway thanks for your replay.

**Comment by WilStead** [comment]
Okay, based on our agreement on the requirements I'll produce a new version of the library that resolves this bug as discussed.

Regarding dynamic object store discovery: reflection is not available in AOT scenarios, so I would prefer to avoid it. A source generated solution might be possible, but I don't think I will attempt that as part of this issue. If you have a strong need for it, please open a new issue.

**Comment by WilStead** [comment]
Version 5 has now been published with the discussed changes.
